app:
  name: 'Token-Tracker'
  version: '1.0.0'

infura:
  network: 'mainnet'
  project-id: 'InputYourProjectId'
  https_endpoint: 'https://mainnet.infura.io/v3/InputYourProjectId'
  websocket_endpoint: 'wss://mainnet.infura.io/ws/v3/InputYourProjectId'

  # track
  eth:
    call_api_maxRetries: 100
    retry_interval: 1
  erc20:
    call_api_maxRetries: 100
    retry_interval: 1

server:
  recorder:
    dev:
      port: 3005
      url_prefix: '/'
      api_url_prefix: ''
    prod:
      port: 8080
      url_prefix: '/recorder'
      api_url_prefix: ''
  tracker:
    dev:
      port: 3006
      url_prefix: '/'
      api_url_prefix: '/api/v1'
    prod:
      port: 8081
      url_prefix: '/tracker'
      api_url_prefix: '/api-tracker/v1'
